[package]
name = "quick_and_dirty"
version = "0.1.0"
authors = ["Sara Moore <sara.moore@recursionpharma.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
